// ============================================================
// workbench86 Editor - Instruction & register tooltips data
// ============================================================

const INSTR_TOOLTIPS = {
  MOV:'Copy source to destination. MOV dst, src',
  XCHG:'Exchange two operands. XCHG dst, src',
  PUSH:'Push value onto stack (SP-=2). PUSH src',
  POP:'Pop value from stack (SP+=2). POP dst',
  PUSHF:'Push FLAGS register onto stack',
  POPF:'Pop FLAGS register from stack',
  LEA:'Load effective address. LEA reg, mem',
  IN:'Read from I/O port. IN AL/AX, port',
  OUT:'Write to I/O port. OUT port, AL/AX',
  XLAT:'Table lookup: AL = DS:[BX+AL]',
  ADD:'Add src to dst, set flags. ADD dst, src',
  SUB:'Subtract src from dst. SUB dst, src',
  MUL:'Unsigned multiply. DX:AX = AX * src',
  IMUL:'Signed multiply. DX:AX = AX * src',
  DIV:'Unsigned divide. AX=DX:AX/src, DX=remainder',
  IDIV:'Signed divide. AX=DX:AX/src, DX=remainder',
  INC:'Increment by 1. INC dst',
  DEC:'Decrement by 1. DEC dst',
  NEG:'Two\'s complement negate. NEG dst',
  CMP:'Compare (SUB without storing). Sets flags',
  CBW:'Convert byte to word: AH = sign-extend AL',
  CWD:'Convert word to double: DX = sign-extend AX',
  DAA:'Decimal adjust after BCD addition',
  DAS:'Decimal adjust after BCD subtraction',
  AAA:'ASCII adjust after addition',
  AAS:'ASCII adjust after subtraction',
  AAM:'ASCII adjust after multiplication',
  AAD:'ASCII adjust before division',
  AND:'Bitwise AND. AND dst, src',
  OR:'Bitwise OR. OR dst, src',
  XOR:'Bitwise XOR. XOR dst, src',
  NOT:'Bitwise NOT (complement). NOT dst',
  TEST:'Bitwise AND without storing. Sets flags',
  SHL:'Shift left (multiply by 2). SHL dst, count',
  SHR:'Shift right unsigned. SHR dst, count',
  SAR:'Shift right arithmetic (preserve sign). SAR dst, count',
  SAL:'Shift left arithmetic (= SHL). SAL dst, count',
  ROL:'Rotate left. ROL dst, count',
  ROR:'Rotate right. ROR dst, count',
  RCL:'Rotate left through carry. RCL dst, count',
  RCR:'Rotate right through carry. RCR dst, count',
  JMP:'Unconditional jump. JMP label',
  JE:'Jump if equal (ZF=1). JE label',
  JNE:'Jump if not equal (ZF=0). JNE label',
  JZ:'Jump if zero (ZF=1). JZ label',
  JNZ:'Jump if not zero (ZF=0). JNZ label',
  JG:'Jump if greater (signed). ZF=0 & SF=OF',
  JGE:'Jump if greater or equal (signed). SF=OF',
  JL:'Jump if less (signed). SF!=OF',
  JLE:'Jump if less or equal (signed). ZF=1 | SF!=OF',
  JA:'Jump if above (unsigned). CF=0 & ZF=0',
  JAE:'Jump if above or equal (unsigned). CF=0',
  JB:'Jump if below (unsigned). CF=1',
  JBE:'Jump if below or equal (unsigned). CF=1 | ZF=1',
  JC:'Jump if carry (CF=1). JC label',
  JNC:'Jump if no carry (CF=0). JNC label',
  JS:'Jump if sign (SF=1). JS label',
  JNS:'Jump if no sign (SF=0). JNS label',
  JO:'Jump if overflow (OF=1). JO label',
  JNO:'Jump if no overflow (OF=0). JNO label',
  JP:'Jump if parity (PF=1). JP label',
  JNP:'Jump if no parity (PF=0). JNP label',
  JCXZ:'Jump if CX=0. JCXZ label',
  LOOP:'Decrement CX, jump if CX!=0. LOOP label',
  LOOPE:'Dec CX, jump if CX!=0 AND ZF=1',
  LOOPNE:'Dec CX, jump if CX!=0 AND ZF=0',
  CALL:'Call subroutine (push IP, jump). CALL label',
  RET:'Return from subroutine (pop IP)',
  INT:'Software interrupt. INT number',
  IRET:'Return from interrupt (pop IP, CS, FLAGS)',
  HLT:'Halt processor until interrupt',
  NOP:'No operation (1 cycle)',
  CLC:'Clear carry flag (CF=0)',
  STC:'Set carry flag (CF=1)',
  CMC:'Complement carry flag',
  CLD:'Clear direction flag (DF=0, forward)',
  STD:'Set direction flag (DF=1, backward)',
  CLI:'Clear interrupt flag (disable interrupts)',
  STI:'Set interrupt flag (enable interrupts)',
  MOVSB:'Move byte DS:[SI] to ES:[DI], update SI,DI',
  MOVSW:'Move word DS:[SI] to ES:[DI], update SI,DI',
  STOSB:'Store AL to ES:[DI], update DI',
  STOSW:'Store AX to ES:[DI], update DI',
  LODSB:'Load DS:[SI] into AL, update SI',
  LODSW:'Load DS:[SI] into AX, update SI',
  CMPSB:'Compare DS:[SI] with ES:[DI], update SI,DI',
  CMPSW:'Compare word DS:[SI] with ES:[DI]',
  SCASB:'Compare AL with ES:[DI], update DI',
  SCASW:'Compare AX with ES:[DI], update DI',
  REP:'Repeat string op CX times',
  REPE:'Repeat while equal (CX!=0 AND ZF=1)',
  REPZ:'Repeat while zero (= REPE)',
  REPNE:'Repeat while not equal (CX!=0 AND ZF=0)',
  REPNZ:'Repeat while not zero (= REPNE)',
  ORG:'Set origin address. ORG 0100H',
  DB:'Define byte(s). DB 0FFH, "text", 0',
  DW:'Define word(s). DW 1234H',
  EQU:'Define constant. name EQU value',
  INCLUDE:'Include file. INCLUDE PATCALLS.INC',
  END:'End of source',
  BYTE:'Size override: byte operand',
  WORD:'Size override: word operand',
  PTR:'Pointer type. BYTE PTR [addr]',
  OFFSET:'Address of label. OFFSET label',
  SEG:'Segment of label. SEG label'
};

const REG_TOOLTIPS = {
  AX:'Accumulator (16-bit). Split: AH (high), AL (low)',
  BX:'Base register (16-bit). Split: BH, BL. Used for addressing',
  CX:'Counter (16-bit). Split: CH, CL. Used by LOOP, shifts',
  DX:'Data register (16-bit). Split: DH, DL. MUL/DIV, I/O',
  AH:'Accumulator high byte. INT function number',
  AL:'Accumulator low byte. I/O data, arithmetic',
  BH:'Base register high byte',BL:'Base register low byte',
  CH:'Counter high byte',CL:'Counter low byte (shift count)',
  DH:'Data high byte',DL:'Data low byte',
  SI:'Source index. String ops source pointer',
  DI:'Destination index. String ops dest pointer',
  SP:'Stack pointer. Points to top of stack',
  BP:'Base pointer. Stack frame access',
  CS:'Code segment (0080H). CS:IP = instruction address',
  DS:'Data segment (0080H). Default for data access',
  SS:'Stack segment (0080H). SS:SP = stack address',
  ES:'Extra segment (0000H). String ops destination',
  IP:'Instruction pointer. Next instruction offset'
};
