// ============================================================
// workbench86 Highlighter Constants - Keyword sets for all languages
// ============================================================

const HL_KEYWORDS = new Set(['MOV','ADD','SUB','MUL','DIV','IMUL','IDIV','INC','DEC','NEG','NOT','AND','OR','XOR','TEST','CMP','SHL','SHR','SAR','SAL','ROL','ROR','RCL','RCR','PUSH','POP','PUSHF','POPF','CALL','RET','JMP','JE','JNE','JZ','JNZ','JG','JGE','JL','JLE','JA','JAE','JB','JBE','JC','JNC','JS','JNS','JO','JNO','JP','JNP','JCXZ','LOOP','LOOPE','LOOPNE','INT','IRET','HLT','NOP','CLC','STC','CMC','CLD','STD','CLI','STI','XCHG','LEA','CBW','CWD','IN','OUT','MOVS','MOVSB','MOVSW','STOS','STOSB','STOSW','LODS','LODSB','LODSW','CMPS','CMPSB','CMPSW','SCAS','SCASB','SCASW','REP','REPE','REPZ','REPNE','REPNZ','DAA','DAS','AAA','AAS','AAM','AAD','XLAT']);
const HL_REGS = new Set(['AX','BX','CX','DX','AH','AL','BH','BL','CH','CL','DH','DL','SI','DI','SP','BP','CS','DS','SS','ES','IP']);
const HL_DIRS = new Set(['ORG','DB','DW','EQU','END','INCLUDE','BYTE','WORD','PTR','OFFSET','SEG']);
const C_KEYWORDS = new Set(['void','int','char','unsigned','signed','short','long','float','double','struct','union','enum','typedef','const','static','extern','volatile','register','return','if','else','for','while','do','switch','case','default','break','continue','goto','sizeof','include','define','auto','inline']);
const C_TYPES = new Set(['PORT1','PORT2','OUTPUT','INPUT','uint8_t','uint16_t','int8_t','int16_t','size_t','NULL','TRUE','FALSE','bool','FILE','stdin','stdout','stderr']);
const PY_BUILTINS = new Set(['print','range','len','int','str','float','list','dict','set','tuple','type','isinstance','enumerate','zip','map','filter','sorted','reversed','input','open','super','self','cls','__init__','__name__','__main__']);
const JAVA_TYPES = new Set(['System','String','Integer','Long','Double','Float','Boolean','Byte','Character','Object','ArrayList','HashMap','List','Map','Set','Thread','Exception','Override','out','println','printf']);
const GO_BUILTINS = new Set(['fmt','Println','Printf','Sprintf','Print','Fprintf','make','len','cap','append','copy','delete','new','panic','recover','close','Println','Scanf','main']);
const PY_KEYWORDS = new Set(['def','return','if','elif','else','for','while','break','continue','pass','import','from','as','class','True','False','None','and','or','not','in','is','lambda','try','except','finally','raise','with','yield','global','nonlocal']);
const JAVA_KEYWORDS = new Set(['public','private','protected','static','void','int','char','byte','short','long','float','double','boolean','class','interface','extends','implements','new','return','if','else','for','while','do','switch','case','default','break','continue','import','package','final','abstract','this','super','true','false','null','String','throws','throw','try','catch','finally']);
const GO_KEYWORDS = new Set(['package','import','func','var','const','type','struct','interface','map','chan','go','select','defer','return','if','else','for','range','switch','case','default','break','continue','fallthrough','true','false','nil','byte','int','uint','string','error','fmt']);
